export const routes = {
    LOGIN: "/",
    SIGNUP: "/signup",
    DASHBOARD: "/dashboard",
    DASHBOARD_WEEKLY:"/dashboard-weekly",
    DASHBOARD_MONTHLY:"/dashboard-monthly",
    DASHBOARD_TARGETS:"/dashboard-target",
    FIELD_AGENTS_REPORT: "/field-agents-report",
    PHONE_AGENTS_REPORT: "/phone-agents-report",
    AU_FIELD_AGENTS_REPORT: "/au-field-agents-report",
    AU_PHONE_AGENTS_REPORT: "/au-phone-agents-report",
    BANK_DETAILS:"/bank-details",
    FIELD_AGENT_DETAILS:"/field-agent-details",
    PHONE_AGENT_DETAILS:"/phone-agent-details",
    AU_AGENT_DETAILS:"/au-agent-details",
    CALCULATOR_MATRIX:"/calculator-matrix",
    CALCULATOR_DATA:"/calculator-data",
    CALCULATOR_GRAPH:"/calculator-graph",
    TARGETS:"/targets",
    MANUAL_DD:"/manual-dd"
}